apiVersion: v2
name: lob-app
description: A generic Helm chart for LOB applications
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - k8s
  - docker
  - registry
  - secret
  - imagePullSecrets
  - python
  - web-service
  - prometheus
  - opentelemetry
maintainers:
  - name: Andriy Kandzyuba
    email: andriy.kandzyuba@dynatrace.com
