name: Remove Dynatrace DynaKube Operator from K8s

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
        default: dev

# Required if using OIDC for authentication in 2026
permissions:
  id-token: write
  contents: read

jobs:
  remove-dynakube:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Print Context Info'
        run: |
          echo "Environment Name: ${{ inputs.environment }}"

      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Setup Kubeconfig'
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: 'Set up Helm'
        uses: azure/setup-helm@v4 # Use a GitHub action to install Helm CLI
        with:
          version: 'latest' # Installs the latest Helm version

      - name: 'Uninstall DynaKube OneAgent with Helm'
        run: |
          helm uninstall ${{ vars.HELM_DYNAKUBE_REPO }} \
          --namespace dynatrace \
          --ignore-not-found

      - name: 'Uninstall Dynatrace Operator with Helm'
        run: |
          helm uninstall dynatrace-operator \
          --namespace dynatrace \
          --ignore-not-found

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_BASE64 }}
        with:
          args: delete namespace dynatrace --ignore-not-found
